import { useMemo, useState } from 'react';
import { Area, AreaChart, Bar, BarChart, CartesianGrid, Cell, ResponsiveContainer, Tooltip, XAxis, YAxis } from 'recharts';
import { Beef, CalendarDays, ChartNoAxesCombined, CircleDollarSign, Gauge, LayoutDashboard, Menu, Scale, Settings2, TrendingUp, WalletCards, X } from 'lucide-react';
import { calculateLot } from './domain/calculations';
import type { LotInput } from './domain/types';
import { Field, SelectField } from './components/Field';
import { MetricCard } from './components/MetricCard';
import { CostList } from './components/CostList';

const initial:LotInput={name:'Lote Confinamento 01',animals:120,entryWeight:365,currentWeight:510,days:105,carcassYield:55,purchaseWeight:365,purchasePrice:11.8,purchaseUnit:'kg',intake:10.5,dietCost:1.42,salePrice:315,otherCosts:[{id:'1',name:'Sanidade',value:32,basis:'animal'},{id:'2',name:'Mão de obra',value:4800,basis:'lote'},{id:'3',name:'Frete',value:2100,basis:'lote'}]};
const brl=new Intl.NumberFormat('pt-BR',{style:'currency',currency:'BRL'}); const num=(v:number,d=1)=>new Intl.NumberFormat('pt-BR',{minimumFractionDigits:d,maximumFractionDigits:d}).format(v);
export function App(){
 const [lot,setLot]=useState(initial); const [tab,setTab]=useState<'dashboard'|'dados'>('dashboard'); const [menu,setMenu]=useState(false);
 const m=useMemo(()=>calculateLot(lot),[lot]);
 const set=<K extends keyof LotInput>(key:K,value:LotInput[K])=>setLot(p=>({...p,[key]:value}));
 const field=(key:keyof LotInput)=>(e:React.ChangeEvent<HTMLInputElement>)=>set(key,Number(e.target.value) as never);
 const costs=[{name:'Compra',value:m.purchaseTotal,color:'#c9b482'},{name:'Alimentação',value:m.feedTotal,color:'#28594b'},{name:'Outros custos',value:m.otherCostsTotal,color:'#82a99c'}];
 const evolution=Array.from({length:8},(_,i)=>{const d=Math.round(lot.days*i/7);return{dia:`D${d}`,peso:lot.entryWeight+m.dailyGain*d}});
 return <div className="app-shell">
  <aside className={menu?'open':''}><div className="brand"><span><Beef/></span><div><b>GESTÃO</b><strong>PECUÁRIA</strong></div><button onClick={()=>setMenu(false)}><X/></button></div><nav><small>VISÃO GERAL</small><button className={tab==='dashboard'?'active':''} onClick={()=>{setTab('dashboard');setMenu(false)}}><LayoutDashboard/> Dashboard</button><button className={tab==='dados'?'active':''} onClick={()=>{setTab('dados');setMenu(false)}}><Settings2/> Análise do lote</button><small>GESTÃO</small><button disabled><Beef/> Lotes <i>Em breve</i></button><button disabled><ChartNoAxesCombined/> Relatórios <i>Em breve</i></button></nav><div className="sidebar-foot"><div className="avatar">GP</div><div><b>Minha propriedade</b><span>Plano demonstração</span></div></div></aside>
  <main><header><button className="menu" onClick={()=>setMenu(true)}><Menu/></button><div><p>Confinamento <span>•</span> Ciclo atual</p><h1>{tab==='dashboard'?'Visão geral do lote':'Análise econômica'}</h1></div><div className="status"><i/> Atualização instantânea</div></header>
  {tab==='dashboard'?<div className="page">
   <section className="welcome"><div><span>DESEMPENHO DO CICLO</span><h2>Olá! Seu lote está ganhando <b>{num(m.dailyGain,2)} kg</b> por dia.</h2><p>Acompanhe os principais indicadores técnicos e financeiros do confinamento.</p></div><button onClick={()=>setTab('dados')}><Settings2 size={18}/> Atualizar dados</button></section>
   <div className="metrics-grid"><MetricCard label="Animais no lote" value={`${num(lot.animals,0)} cabeças`} icon={Beef}/><MetricCard label="Peso de entrada" value={`${num(lot.entryWeight)} kg`} icon={Scale}/><MetricCard label="Peso atual / saída" value={`${num(lot.currentWeight)} kg`} icon={Scale}/><MetricCard label="GMD" value={`${num(m.dailyGain,2)} kg/dia`} icon={TrendingUp}/><MetricCard label="Dias de confinamento" value={`${num(lot.days,0)} dias`} icon={CalendarDays}/><MetricCard label="Custo cabeça/dia" value={brl.format(m.costPerHeadDay)} icon={WalletCards}/><MetricCard label="Custo da @ produzida (PV)" value={brl.format(m.producedArrobaCost)} icon={CircleDollarSign}/><MetricCard label="Investimento total" value={brl.format(m.investment)} icon={WalletCards}/></div>
   <div className="financial"><MetricCard featured label="Receita projetada" value={brl.format(m.revenue)} icon={TrendingUp}/><MetricCard featured label="Margem por animal" value={brl.format(m.marginPerAnimal)} icon={Gauge} tone={m.marginPerAnimal>=0?'positive':'negative'}/><MetricCard featured label="Margem total" value={brl.format(m.result)} icon={CircleDollarSign} tone={m.result>=0?'positive':'negative'}/><MetricCard featured label="ROI estimado" value={`${num(m.roi,2)}%`} icon={ChartNoAxesCombined} tone={m.roi>=0?'positive':'negative'}/></div>
   <div className="charts"><article className="panel"><div className="panel-title"><div><h3>Evolução de peso</h3><p>Projeção com base no GMD atual</p></div><span className="legend"><i/> Peso vivo (kg)</span></div><div className="chart"><ResponsiveContainer><AreaChart data={evolution} margin={{left:-15,right:12}}><defs><linearGradient id="area" x1="0" y1="0" x2="0" y2="1"><stop offset="0" stopColor="#28594b" stopOpacity=".25"/><stop offset="1" stopColor="#28594b" stopOpacity="0"/></linearGradient></defs><CartesianGrid strokeDasharray="3 3" vertical={false}/><XAxis dataKey="dia"/><YAxis domain={['dataMin - 20','dataMax + 15']}/><Tooltip formatter={v=>`${num(Number(v))} kg`}/><Area type="monotone" dataKey="peso" stroke="#28594b" strokeWidth={3} fill="url(#area)"/></AreaChart></ResponsiveContainer></div></article>
   <article className="panel"><div className="panel-title"><div><h3>Composição do investimento</h3><p>Distribuição por categoria</p></div></div><div className="chart"><ResponsiveContainer><BarChart data={costs} layout="vertical" margin={{left:10,right:18}}><CartesianGrid strokeDasharray="3 3" horizontal={false}/><XAxis type="number" tickFormatter={v=>`${Math.round(v/1000)} mil`}/><YAxis dataKey="name" type="category" width={92}/><Tooltip formatter={v=>brl.format(Number(v))}/><Bar dataKey="value" radius={[0,6,6,0]}>{costs.map(c=><Cell key={c.name} fill={c.color}/>)}</Bar></BarChart></ResponsiveContainer></div></article></div>
   <div className="insight"><span><Gauge/></span><div><b>Ponto de equilíbrio</b><p>O preço mínimo para cobrir aquisição e custos de produção é <strong>{brl.format(m.breakEven)}/@</strong>.</p></div><small>Venda esperada<br/><b>{brl.format(lot.salePrice)}/@</b></small></div><div className="summary-strip"><span><small>@ produzida equivalente (PV)</small><b>{num(m.liveArrobasProducedPerAnimal,2)} @/animal</b></span><span><small>Peso de carcaça projetado</small><b>{num(m.carcassWeightPerAnimal,1)} kg/animal</b></span><span><small>@ de carcaça na saída</small><b>{num(m.carcassArrobasPerAnimal,2)} @/animal</b></span></div>
  </div>:<div className="page form-page">
   <div className="form-intro"><div><h2>Premissas do ciclo</h2><p>Preencha os dados reais. Os indicadores são recalculados automaticamente.</p></div><span><i/> Cálculo em tempo real</span></div>
   <section className="form-panel"><div className="section-title"><span>01</span><div><h3>Dados do lote</h3><p>Informações zootécnicas do ciclo</p></div></div><div className="form-grid"><Field label="Nome do lote" value={lot.name} onChange={e=>set('name',e.target.value)}/><Field label="Quantidade de animais" type="number" min="0" suffix="cabeças" value={lot.animals||''} onChange={field('animals')}/><Field label="Peso médio de entrada" type="number" min="0" suffix="kg" value={lot.entryWeight||''} onChange={field('entryWeight')}/><Field label="Peso atual / saída" type="number" min="0" suffix="kg" value={lot.currentWeight||''} onChange={field('currentWeight')}/><Field label="Dias no sistema" type="number" min="0" suffix="dias" value={lot.days||''} onChange={field('days')}/><Field label="Rendimento de carcaça" type="number" min="0" max="100" suffix="%" value={lot.carcassYield||''} onChange={field('carcassYield')}/></div><div className="calculated"><TrendingUp/><span>GMD calculado</span><b>{num(m.dailyGain,2)} kg/dia</b><small>Ganho: {num(m.weightGain)} kg · {num(m.liveArrobasProducedPerAnimal,2)} @ eq. PV/animal</small></div><div className="summary-strip"><span><small>@ produzida – equivalente em peso vivo</small><b>{num(m.liveArrobasProducedPerAnimal,2)} @/animal</b></span><span><small>Peso de carcaça projetado</small><b>{num(m.carcassWeightPerAnimal,1)} kg/animal</b></span><span><small>@ de carcaça na saída</small><b>{num(m.carcassArrobasPerAnimal,2)} @/animal</b></span></div></section>
   <section className="form-panel"><div className="section-title"><span>02</span><div><h3>Compra e venda</h3><p>Capital de aquisição e projeção de receita</p></div></div><div className="form-grid"><Field label="Peso de compra" type="number" min="0" suffix="kg" value={lot.purchaseWeight||''} onChange={field('purchaseWeight')}/><SelectField label="Unidade do preço" value={lot.purchaseUnit} onChange={e=>set('purchaseUnit',e.target.value as 'kg'|'arroba')}><option value="kg">Por kg</option><option value="arroba">Por arroba (@)</option></SelectField><Field label={`Preço de compra por ${lot.purchaseUnit==='kg'?'kg':'@'}`} type="number" min="0" step="0.01" suffix="R$" value={lot.purchasePrice||''} onChange={field('purchasePrice')}/><Field label="Preço esperado de venda" type="number" min="0" step="0.01" suffix="R$/@" value={lot.salePrice||''} onChange={field('salePrice')}/></div><div className="summary-strip"><span><small>Compra por animal</small><b>{brl.format(m.purchasePerAnimal)}</b></span><span><small>Compra total do lote</small><b>{brl.format(m.purchaseTotal)}</b></span><span><small>Receita projetada</small><b>{brl.format(m.revenue)}</b></span></div></section>
   <section className="form-panel"><div className="section-title"><span>03</span><div><h3>Alimentação</h3><p>Consumo e custo da dieta</p></div></div><div className="form-grid two"><Field label="Consumo de matéria natural" type="number" min="0" step="0.1" suffix="kg/animal/dia" value={lot.intake||''} onChange={field('intake')}/><Field label="Custo da dieta" type="number" min="0" step="0.01" suffix="R$/kg" value={lot.dietCost||''} onChange={field('dietCost')}/></div><div className="summary-strip"><span><small>Custo animal/dia</small><b>{brl.format(m.feedPerHeadDay)}</b></span><span><small>Custo animal/período</small><b>{brl.format(m.feedPerAnimal)}</b></span><span><small>Alimentação do lote</small><b>{brl.format(m.feedTotal)}</b></span></div></section>
   <section className="form-panel"><div className="section-title"><span>04</span><div><h3>Outros custos</h3><p>Despesas operacionais adicionais</p></div></div><CostList costs={lot.otherCosts} onChange={c=>set('otherCosts',c)}/></section>
  </div>}
  </main>{menu&&<div className="overlay" onClick={()=>setMenu(false)}/>}</div>;
}
